# https://github.com/xianmin/hugo-theme-jane
# https://github.com/xianmin/hugo-theme-jane/blob/master/exampleSite/config.toml

baseURL = "/"
title = "impyq"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = true
paginate = 8
copyright = "impyq"

enableGitInfo = true  # 可根据 Git 中的提交生成最近更新记录。

defaultContentLanguage = "zh-cn"
[languages.zh-cn]
  languageCode = "zh-cn"

pygmentsCodeFences = true
pygmentsUseClasses = true

[author]
  name = "impyq"

[sitemap]                 
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             
  name = "主页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "标签"
  weight = 20
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "分类"
  weight = 30
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "随手记"
  weight = 40
  identifier = "notes"
  url = "/notes/"

[params]
  since = "2018"
  homeFullContent = false
  logoTitle = "impyq"
  keywords = ["impyq", "博客", "笔记"]
  description = "个人博客，学习笔记，督促自己不断进步"
  dateFormatToUse = "2006-01-02"
  toc = true
  photoswipe = true
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

[params.social]
  g-github = "https://github.com/yenkeia/"
